### ISSUE TITLE
Grab bag of small things

### ISSUE THREAD

**Issue by robinwhittleton** [drgrigg/karel-capek_the-absolute-at-large#1]
general:
- clean removes an errant space
- build-images is making some changes

cover.svg:
- Missing the translator from the title

content.opf:
- Maybe don’t start the blurb with a reference to RUR?

chapter-7:
- “shares were quoted at 1470 yesterday” needs a thousands separator

chapter-26:
- Kralove in the title, but Králové throughout the chapter. Will need to regen ToC after fixing.

endnotes:
- Should presumably be fiction instead of non-fiction?

**Comment by drgrigg** [comment]
Fixed all these.

The build-images issue was the fact that I hadn't properly updated all the files when I added the translator.

The endnotes issue is interesting, though I've changed it. Out of curiosity, what do we do if we have endnotes which mix fiction and non-fiction notes?

**Comment by robinwhittleton** [comment]
I’m pretty sure I’ve tagged individual endnotes with fiction or non-fiction before, but despite my best searching I can’t find any instances in the corpus now.

**Comment by robinwhittleton** [comment]
One last thing: the colophon says originally published in 1927 and translated in 1927, but the longdesc says written in 1922. Is that correct?

**Comment by drgrigg** [comment]
The Czech version was published in 1922, the English edition came out in 1927. I wasn’t quite sure how to handle that in the colophon.

Regards,

David

**Comment by robinwhittleton** [comment]
Original publication date first, then date of publication of the translated version second: https://standardebooks.org/manual/1.7.4/single-page#6.6.6.1.2.1. Not sure what we do if the date of translation and date of publication of the translation differ, but we don’t have to worry about that here.

**Comment by drgrigg** [comment]
OK, that should be fixed now.

As an aside, this was the first time I’ve edited my repository via the Github app on my iPad, so I hope it worked!

Regards,

David
